name: sant_lipi
description: A unicode font for extraordinary Gurmukhi.
version: 0.17.0
repository: https://github.com/shabados/SantLipi
topics:
  - font
  - gurmukhi
  - punjabi

environment:
  sdk: ^3.0.0
